### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by panic6locc** [ytmcgamer/FortniteSourceUPDATED#2]
Failed to find module "dxgi.dll"

**sorry if i'm bothering you i'm new to fortnite cheats ^^**

**Comment by TENSITY6666** [comment]
download this and run this this is like a mapper so just run this then inject in game
https://cdn.discordapp.com/attachments/759494818652094526/762256747020419072/ALTdrv2.exe

**Comment by ytmcgamer** [comment]
yes

**Comment by pax20die** [comment]
bruh driver
![image](https://user-images.githubusercontent.com/37377502/102927244-a564b580-44a7-11eb-8c3f-4558f7f49232.png)
